version: "3.9"

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - 8443:8443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
      - ./group23.crt://etc/nginx/group23.crt
      - ./group23.key://etc/nginx/group23.key
    
    depends_on:
      - webapp

  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/usr/src/app
    environment:
      - DATABASE_URL=mysql://chatuser:chatpassword@db/chatdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=chatdb
      - MYSQL_USER=chatuser
      - MYSQL_PASSWORD=chatpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
